TM_HOME ?= ../
AMREX_HOME ?= ../../amrex

DIM = 3

COMP = gnu

DEBUG	= TRUE

USE_MPI       = FALSE
USE_OMP       = FALSE
USE_ACC       = FALSE
USE_CUDA      = FALSE

TINY_PROFILE  = TRUE
USE_PARTICLES = TRUE

PRECISION     = DOUBLE

Bpack   :=
Blocs   := . 

include ../Make.Transmogrifier
